recipientsTO:
  - 'main_recipient@example.com'
recipientsCC:
  - 'cc_recipient1@example.com'
  - 'cc_recipient2@example.com'

email_content:
  Monday: 
    start: "Treść wiadomości rozpoczynającej pracę w poniedziałek."
    stop: "Treść e-maila kończącego pracę na poniedziałek. "
  Tuesday: 
    start: "Treść wiadomości rozpoczynającej pracę we wtorek."
    stop: "Treść e-maila kończącego pracę na wtorek. "
  Wednesday: 
    start: "Treść wiadomości rozpoczynającej pracę w środę."
    stop: "Treść e-maila kończącego pracę na środę. "
  Thurstday: 
    start: "Treść wiadomości rozpoczynającej pracę w czwartek."
    stop: "Treść e-maila kończącego pracę na czwartek. "
  Friday: 
    start: "Treść wiadomości rozpoczynającej pracę w piątek."
    stop: "Treść e-maila kończącego pracę na piątek. "
  Saturday: 
    start: "Treść wiadomości rozpoczynającej pracę w sobotę."
    stop: "Treść e-maila kończącego pracę na sobotę. "
  Sunday: 
    start: "Treść wiadomości rozpoczynającej pracę w niedzielę."
    stop: "Treść e-maila kończącego pracę na niedzielę. "
  

exceptions:
  - 2024-05-10
  - 2024-05-17
  