recipients:
  - recipient1@example.com
  - recipient2@example.com
  - recipient3@example.com

start_content: |
  Treść e-maila o początku pracy.

end_content:
  monday: |
    Treść e-maila kończącego pracę na poniedziałek.
  tuesday: |
    Treść e-maila kończącego pracę na wtorek.
  wednesday: |
    Treść e-maila kończącego pracę na środę.
  thurstday: |
    Treść e-maila kończącego pracę na czwartek.
  friday: |
    Treść e-maila kończącego pracę na piątek.
  saturday: |
    Treść e-maila kończącego pracę na sobotę.
  sunday: |
    Treść e-maila kończącego pracę na niedzielę
  

exceptions:
  - 2024-05-10
  - 2024-05-17
  